# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('fid', models.SmallIntegerField()),
                ('ord', models.CharField(max_length=20, null=True, blank=True)),
                ('fam', models.CharField(max_length=20, null=True, blank=True)),
                ('genus', models.CharField(max_length=20)),
                ('species', models.CharField(max_length=20, null=True, blank=True)),
                ('species_id', models.CharField(max_length=40, serialize=False, primary_key=True)),
                ('synonyms', models.CharField(max_length=300, null=True, blank=True)),
                ('common_name_1', models.CharField(max_length=40)),
                ('common_name_2', models.CharField(max_length=50, null=True, blank=True)),
                ('common_name_3', models.CharField(max_length=50, null=True, blank=True)),
                ('common_name_4', models.CharField(max_length=50, null=True, blank=True)),
                ('common_name_5', models.CharField(max_length=50, null=True, blank=True)),
                ('common_name_6', models.CharField(max_length=50, null=True, blank=True)),
                ('iucn_status', models.CharField(max_length=4, null=True, blank=True)),
                ('red_list_criteria', models.CharField(max_length=100, null=True, blank=True)),
                ('year_assessed', models.IntegerField(null=True, blank=True)),
                ('population_trend', models.CharField(max_length=20, null=True, blank=True)),
                ('coloniality', models.CharField(max_length=5, null=True, blank=True)),
                ('breeding_dist', models.CharField(max_length=10, null=True, blank=True)),
                ('nest_locations', models.CharField(max_length=15, null=True, blank=True)),
                ('hatchling_type', models.CharField(max_length=5, null=True, blank=True)),
            ],
            options={
                'db_table': 'species',
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('feature_id', models.SmallIntegerField(serialize=False, primary_key=True)),
                ('female_mass_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('female_mass_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('female_mass_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('female_mass_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('male_mass_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('male_mass_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('male_mass_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('male_mass_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('clutch_size_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('clutch_size_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('cluth_size_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('clutch_size_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('clutch_interval', models.CharField(max_length=50, null=True, blank=True)),
                ('incubation_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('incubation_period_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('incubtaion_period_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('incubation_period_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('fledging_period_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('fledging_period_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('fledging_period_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('fledging_period_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('max_growth_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('max_growth_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('max_growth_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('max_growth_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('post_fledge_care_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('post_fledge_care_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('post_fledge_care_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('post_fledge_care_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('age_first_breed_mean', models.CharField(max_length=10, null=True, blank=True)),
                ('age_first_breed_lower', models.IntegerField(null=True, blank=True)),
                ('age_first_breed_upper', models.IntegerField(null=True, blank=True)),
                ('age_first_breed_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('foraging_distance', models.CharField(max_length=50, null=True, blank=True)),
                ('wingspan_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('wingspan_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('wingspan_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('wingspan_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('max_age_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('max_age_lower', models.IntegerField(null=True, blank=True)),
                ('max_age_upper', models.IntegerField(null=True, blank=True)),
                ('max_age_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('annual_survival_mean', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('annual_survival_lower', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('annual_survival_upper', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('annual_survival_uncertainty', models.CharField(max_length=50, null=True, blank=True)),
                ('citation', models.TextField(null=True, blank=True)),
                ('username', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=30)),
                ('species', models.ForeignKey(to='app.Species')),
            ],
            options={
                'db_table': 'traits',
                'verbose_name': 'Traits',
                'verbose_name_plural': 'Traits',
            },
        ),
    ]
